In [1]:
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
from matplotlib.gridspec import GridSpec
import CompleteHist as ch
%matplotlib

Using matplotlib backend: TkAgg


In [2]:
def plotSlips(data,fit,slips):
    ch.plotFig(data,fit)
    holdx = list()
    holdy = list()
    for i in slips:
        holdx.append(i[0])
    for i in holdx:
        holdy.append(data[1][ch.search(data,i)])
    plt.scatter(holdx,holdy,s=50,color='k')

In [3]:
bf = np.load('73bf.npy')
ch.parsePrune('soft')
d = ch.getPrune()

In [5]:
ch.plotFig(d[0],bf[0][0])

In [7]:
ch.bestFits = bf

In [8]:
hists = ch.mainRun(dV=0.02)

In [307]:
np.save('73hist',hists)

In [11]:
plt.hist(hists)

(array([ 14.,  51.,  19.,  12.,  27.,  64.,   0.,  40.,   0.,  14.]),
 array([ 1.15849272,  1.19288834,  1.22728397,  1.26167959,  1.29607521,
         1.33047083,  1.36486646,  1.39926208,  1.4336577 ,  1.46805333,
         1.50244895]),
 <a list of 10 Patch objects>)

In [8]:
ch.plotFig(d[2],bf[2][0])

In [291]:
plotSlips(d[16],bf[16][0],a)

In [282]:
a

array([[-25.1047    ,   5.741     ,   0.96294139],
       [-24.98083   ,   5.741     ,   0.96294139],
       [-24.41924   ,   5.741     ,   0.96294139],
       [-14.976075  ,   5.741     ,   1.1162834 ],
       [-14.91024   ,   5.741     ,   1.1162834 ],
       [-14.760315  ,   5.741     ,   1.1162834 ],
       [-14.722375  ,   5.741     ,   1.1162834 ],
       [-14.53818   ,   5.741     ,   1.1162834 ],
       [-14.4913    ,   5.741     ,   1.1162834 ],
       [-14.46399   ,   5.741     ,   1.1162834 ],
       [-14.23288   ,   5.741     ,   1.1162834 ],
       [-14.162015  ,   5.741     ,   1.1162834 ],
       [-14.060865  ,   5.741     ,   1.1162834 ],
       [-13.93628   ,   5.741     ,   1.1162834 ],
       [-13.74929   ,   5.741     ,   1.1162834 ],
       [-13.701825  ,   5.741     ,   1.1162834 ],
       [-13.57985   ,   5.741     ,   1.1162834 ],
       [-13.55446   ,   5.741     ,   1.1162834 ],
       [-13.52056   ,   5.741     ,   1.1162834 ],
       [-13.428695  ,   5.741  

In [265]:
bf[13][5][9]

1.2769099633689405

In [292]:
bf73.append(bf[16][0])

In [293]:
bf[16] = [np.array(bf73[16])]

In [304]:
np.save('73se',np.array(se73))

In [286]:
bf[15][1][0] -= 0.5
ch.plotFig(d[15],bf[15][1])

In [287]:
bf73.append(np.zeros(12))
bf[15] = [np.array(bf73[15])]

In [300]:
se73 = list()
for i in range(17):
    hold = ch.countEdge(i,dtype='73',dV=0.02)
    se73.append(np.array(hold))
se73 = np.array(se73)

In [302]:
se73[0]

array([[-26.302665  ,   5.7485    ,   1.50244895],
       [-25.47433   ,   5.7485    ,   1.50244895],
       [-25.20787   ,   5.7485    ,   1.50244895],
       [-25.136515  ,   5.7485    ,   1.50244895],
       [-24.96162   ,   5.7485    ,   1.50244895],
       [-24.832775  ,   5.7485    ,   1.50244895],
       [-24.381755  ,   5.7485    ,   1.50244895],
       [-23.87108   ,   5.7485    ,   1.50244895],
       [-23.53994   ,   5.7485    ,   1.50244895],
       [-23.418455  ,   5.7485    ,   1.50244895],
       [-23.328765  ,   5.7485    ,   1.50244895],
       [-22.641185  ,   5.7485    ,   1.50244895],
       [-22.53995   ,   5.7485    ,   1.48249462],
       [-20.771625  ,   5.7485    ,   1.48249462]])